#!/bin/bash

JAR_DIR=$(dirname "$0")
JAR_FILE="$JAR_DIR/target/scala-2.13/distributedsorting.jar"
COMMAND="distributedsorting.master.Master"

# 인수의 개수 확인 (워커 수)
if [ -z "$1" ]; then
    echo "Usage: $0 <# of workers>"
    exit 1
fi

# 자바 실행 명령
# 예: java -cp target/scala-2.13/distributedsorting.jar master 3
java -cp "$JAR_FILE" "$COMMAND" "$1"